apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-code4

  description: "Provides enhanced functionalities for testing code, serving developers looking to improve their testing processes."
  annotations:
    github.com/project-slug: nimeshjain1/test-code4
    backstage.io/techdocs-ref: dir:.
    catalog-agent/auto-heal: 'true'
    catalog-agent/healing-mode: 'pull-request'
    catalog-agent/readme-path: 'README.md'
  tags:
    - experimental
spec:
  type: service
  lifecycle: experimental
  owner: user:default/nimeshjain1

